//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiticsManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentVehicle
    {
        public int shipment_id { get; set; }
        public int vehicle_id { get; set; }
        public Nullable<System.DateTime> load_date { get; set; }
        public Nullable<System.DateTime> unload_date { get; set; }
    
        public virtual Shipment Shipment { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
