//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiticsManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRoute
    {
        public int vehicle_route_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public System.DateTime assignment_date { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
